
Description: Gets list of a company workers by name
--1
SELECT PERSON.NAME
FROM PAID_BY INNER JOIN PERSON
ON PAID_BY.PER_ID = PERSON.PER_ID
INNER JOIN JOB_LISTING
ON PAID_BY.LISTING_ID = JOB_LISTING.LISTING_ID
WHERE COMP_ID = 13;


Description: Gets list of a company staff by salary in descending order
--2
SELECT NAME, PAY_RATE 
FROM PERSON INNER JOIN PAID_BY
ON PERSON.PER_ID = PAID_BY.PER_ID
INNER JOIN JOB_LISTING
ON JOB_LISTING.LISTING_ID = PAID_BY.LISTING_ID
INNER JOIN JOB 
ON JOB_LISTING.JOB_CODE = JOB.JOB_CODE
WHERE COMP_ID = 13 
AND PAY_TYPE = 'salary'
ORDER BY PAY_RATE DESC;


Description: Gets all jobs a person is currently holding and worked in the
past
--4
SELECT PER_ID, JOB_TITLE, START_DATE, END_DATE
FROM JOB_HISTORY NATURAL JOIN JOB
WHERE PER_ID=2;



--13
-- Provided query. 


--14
-- Provided query.


Description: Gets a list of people who miss only one skill for a specified job
--16
SELECT NAME
FROM PERSON
WHERE NOT EXISTS (
     SELECT JOB_SKILL.KS_CODE, KNOWLEDGE_SKILL.TITLE 
FROM JOB_SKILL LEFT JOIN KNOWLEDGE_SKILL 
ON JOB_SKILL.KS_CODE = KNOWLEDGE_SKILL.KS_CODE
WHERE JOB_CODE=67
MINUS
SELECT PERSON_SKILL.KS_CODE, KNOWLEDGE_SKILL.TITLE 
FROM PERSON_SKILL LEFT JOIN KNOWLEDGE_SKILL 
ON PERSON_SKILL.KS_CODE = KNOWLEDGE_SKILL.KS_CODE
);



Description: Gets the skillID and the number of people in the missing-one
list for a given job in the ascending order of the people counts.
--17
SELECT DISTINCT PERSON_SKILL.KS_CODE, COUNT(DISTINCT NAME) AS TOTAL_COUNT
FROM (
  SELECT NAME
FROM PERSON
WHERE NOT EXISTS (
     SELECT JOB_SKILL.KS_CODE, KNOWLEDGE_SKILL.TITLE 
FROM JOB_SKILL LEFT JOIN KNOWLEDGE_SKILL 
ON JOB_SKILL.KS_CODE = KNOWLEDGE_SKILL.KS_CODE
WHERE JOB_CODE=67
MINUS
SELECT PERSON_SKILL.KS_CODE, KNOWLEDGE_SKILL.TITLE 
FROM PERSON_SKILL LEFT JOIN KNOWLEDGE_SKILL 
ON PERSON_SKILL.KS_CODE = KNOWLEDGE_SKILL.KS_CODE)
), PERSON_SKILL, JOB
WHERE JOB_CODE=91
GROUP BY PERSON_SKILL.KS_CODE
ORDER BY TOTAL_COUNT ASC;





Description: Gets the list of person who miss the least number of skills and 
reported the least number
--18
WITH NEEDED_SKILLS AS (
SELECT KS_CODE
FROM JOB_SKILL
WHERE JOB_CODE=23),

COUNT_NEEDED_SKILLS(PER_ID, MISSING_AMOUNT) AS (
SELECT PER_ID, COUNT(KS_CODE)
FROM PERSON P, NEEDED_SKILLS
WHERE KS_CODE IN (
SELECT KS_CODE 
FROM NEEDED_SKILLS
MINUS
SELECT KS_CODE 
FROM PERSON_SKILL
WHERE PER_ID=P.PER_ID)
GROUP BY PER_ID
)
SELECT PER_ID, MISSING_AMOUNT
FROM COUNT_NEEDED_SKILLS
WHERE MISSING_AMOUNT = (
SELECT MIN(MISSING_AMOUNT)
FROM COUNT_NEEDED_SKILLS)
ORDER BY PER_ID ASC;





Description: Gets a list of the people IDs and the number of missing skills
for the people who miss only up to 2-skills in ascending order of missing
skills
--19



Description: Gets a list of each skillID and the number of people who need
it in descending order of the people counts
--20

